// frontend/src/lib/components/VideoUpload.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  let progress = 0;
  async function handleDrop(event: DragEvent) {
    event.preventDefault();
    const file = event.dataTransfer?.files[0];
    if (file && file.type.startsWith('video/')) {
      dispatch('upload', { file });
      const interval = setInterval(() => {
        progress = Math.min(progress + 10, 100);
        if (progress === 100) clearInterval(interval);
      }, 500);
    }
  }
</script>

<div on:dragover|preventDefault on:drop={handleDrop} class="drop-zone">
  <p>Drop video here (MP4, AVI, etc.)</p>
  {#if progress > 0}
    <progress value={progress} max="100">{progress}%</progress>
  {/if}
</div>

<style>
  .drop-zone {
    border: 2px dashed #ccc;
    padding: 2rem;
    text-align: center;
    cursor: pointer;
  }
</style>

// frontend/src/components/VideoUpload.tsx
import { useState } from 'react';

export default function VideoUpload({ onUpload }: { onUpload: (file: File) => void }) {
  const [progress, setProgress] = useState(0);

  const handleDragOver = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
  };

  const handleDrop = async (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    const file = event.dataTransfer.files[0];
    if (file && file.type.startsWith('video/')) {
      onUpload(file);
      const interval = setInterval(() => {
        setProgress((prev) => {
          const next = Math.min(prev + 10, 100);
          if (next === 100) clearInterval(interval);
          return next;
        });
      }, 500);
    }
  };

  return (
    <div
      onDragOver={handleDragOver}
      onDrop={handleDrop}
      style={{
        border: '2px dashed #ccc',
        padding: '2rem',
        textAlign: 'center',
        cursor: 'pointer'
      }}
    >
      <p>Drop video here (MP4, AVI, etc.)</p>
      {progress > 0 && (
        <progress value={progress} max="100">
          {progress}%
        </progress>
      )}
    </div>
  );
}
